### ISSUE TITLE
VersionRecognition对象用无参构造函数无法初始化

### ISSUE THREAD

**Issue by GXNU156489** [TimelineSec/ATTCK-Tools-library#4]
我认为在ExpMain.java和VersionRecognition.java中，部分代码有问题。

VersionRecognition.java中创建了带参的构造函数，没有预留无参的构造函数
![image](https://user-images.githubusercontent.com/36919834/105702554-ec324900-5f46-11eb-924f-9d822da6277b.png)

而在ExpMain.java中却使用无参的方式来初始化VersionRecognition对象
![image](https://user-images.githubusercontent.com/36919834/105702619-03713680-5f47-11eb-8538-62cb38d4a1b6.png)

**Comment by shuimuLiu** [comment]
构造函数的特点
1、函数名与类名相同
2、不用定义返回值类型。（不同于void类型返回值，void是没有具体返回值类型；构造函数是连类型都没有）
3、不可以写return语句。（返回值类型都没有，故不需要return语句）
注：一般函数不能调用构造函数，只有构造函数才能调用构造函数。
